version: '3.8'

services:
  plannerfin:
    build: .
    container_name: plannerfin-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - ./server/data:/app/server/data
