import {
  Account,
  CreditCard,
  Category,
  Transaction,
  Budget,
  Goal,
  Debt,
  InvestmentAsset,
  FamilyMember,
  NotificationItem,
  TransactionSeries,
} from '../types';
import { DEFAULT_CATEGORIES } from './defaultCategories';

export interface FullDemoStore {
  accounts: Account[];
  cards: CreditCard[];
  categories: Category[];
  transactions: Transaction[];
  transactionSeries?: TransactionSeries[];
  budgets: Budget[];
  goals: Goal[];
  debts: Debt[];
  investments: InvestmentAsset[];
  familyMembers: FamilyMember[];
  notifications?: NotificationItem[];
  userProfile?: {
    name: string;
    email: string;
    phone: string;
    currency: string;
    showValues?: boolean;
  };
}

export function generateRealisticDemoStore(): FullDemoStore {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const currentMonthPrefix = `${year}-${month}`;

  // Helper date generators for current and relative months
  const getDateInCurrentMonth = (day: number) => {
    const target = new Date(year, now.getMonth() + 1, 0);
    const safeDay = Math.min(day, target.getDate());
    return `${currentMonthPrefix}-${String(safeDay).padStart(2, '0')}`;
  };

  const getOffsetMonthPrefix = (offset: number) => {
    const d = new Date(year, now.getMonth() + offset, 1);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
  };

  const getDateInOffsetMonth = (offset: number, day: number) => {
    const target = new Date(year, now.getMonth() + offset + 1, 0);
    const safeDay = Math.min(day, target.getDate());
    return `${getOffsetMonthPrefix(offset)}-${String(safeDay).padStart(2, '0')}`;
  };

  // 1. ACCOUNTS (Contas Bancárias)
  const accounts: Account[] = [
    {
      id: 'acc-demo-nubank',
      name: 'Nubank Conta',
      type: 'checking',
      balance: 4850.00,
      initialBalance: 2000.00,
      institution: 'Nubank',
      color: '#820ad1',
      includeInTotal: true,
    },
    {
      id: 'acc-demo-itau',
      name: 'Itaú Personnalité',
      type: 'checking',
      balance: 8920.50,
      initialBalance: 5000.00,
      institution: 'Itaú',
      color: '#ec7000',
      includeInTotal: true,
    },
    {
      id: 'acc-demo-xp',
      name: 'XP Investimentos',
      type: 'investment',
      balance: 15400.00,
      initialBalance: 10000.00,
      institution: 'XP Investimentos',
      color: '#000000',
      includeInTotal: true,
    },
    {
      id: 'acc-demo-inter',
      name: 'Banco Inter Reserva',
      type: 'investment',
      balance: 6200.00,
      initialBalance: 3000.00,
      institution: 'Banco Inter',
      color: '#ff7a00',
      includeInTotal: true,
    },
    {
      id: 'acc-demo-c6',
      name: 'C6 Bank',
      type: 'checking',
      balance: 1650.00,
      initialBalance: 1000.00,
      institution: 'C6 Bank',
      color: '#242424',
      includeInTotal: true,
    },
    {
      id: 'acc-demo-carteira',
      name: 'Carteira Física (Dinheiro)',
      type: 'cash',
      balance: 380.00,
      initialBalance: 200.00,
      institution: 'Carteira',
      color: '#10b981',
      includeInTotal: true,
    },
  ];

  // 2. CREDIT CARDS (Cartões de Crédito)
  const cards: CreditCard[] = [
    {
      id: 'card-demo-nubank',
      name: 'Nubank Ultravioleta',
      brand: 'Mastercard',
      limit: 15000,
      closingDay: 27,
      dueDay: 5,
      color: '#820ad1',
      defaultAccountId: 'acc-demo-nubank',
    },
    {
      id: 'card-demo-itau',
      name: 'Itaú Mastercard Black',
      brand: 'Mastercard',
      limit: 30000,
      closingDay: 20,
      dueDay: 28,
      color: '#ec7000',
      defaultAccountId: 'acc-demo-itau',
    },
    {
      id: 'card-demo-c6',
      name: 'C6 Carbon Black',
      brand: 'Mastercard',
      limit: 10000,
      closingDay: 15,
      dueDay: 22,
      color: '#242424',
      defaultAccountId: 'acc-demo-c6',
    },
    {
      id: 'card-demo-inter',
      name: 'Inter Mastercard Gold',
      brand: 'Mastercard',
      limit: 5000,
      closingDay: 28,
      dueDay: 5,
      color: '#ff7a00',
      defaultAccountId: 'acc-demo-inter',
    },
  ];

  // 3. CATEGORIES
  const categories: Category[] = DEFAULT_CATEGORIES;

  // 4. FAMILY MEMBERS
  const familyMembers: FamilyMember[] = [
    {
      id: 'mem-demo-owner',
      name: 'Carlos Eduardo (Você)',
      email: 'demo@finly.com',
      phone: '11999998888',
      role: 'admin',
      status: 'active',
      isOwner: true,
      type: 'linked',
      joinedAt: '01/01/2026',
    },
    {
      id: 'mem-demo-partner',
      name: 'Mariana Silveira',
      email: 'mariana.demo@finly.com',
      phone: '11988887777',
      role: 'editor',
      status: 'active',
      isOwner: false,
      type: 'linked',
      joinedAt: '15/01/2026',
    },
    {
      id: 'mem-demo-son',
      name: 'Pedro Silveira',
      email: 'pedro.demo@finly.com',
      role: 'viewer',
      status: 'active',
      isOwner: false,
      type: 'unlinked',
      joinedAt: '01/02/2026',
    },
  ];

  // 5. TRANSACTIONS
  const transactions: Transaction[] = [
    // --- RECEITAS DO MÊS ---
    {
      id: 'tx-rec-salario',
      description: 'Salário Mensal Líquido (Tech Lead)',
      amount: 10800.00,
      date: getDateInCurrentMonth(5),
      type: 'income',
      status: 'completed',
      categoryId: 'cat-rec-trabalho',
      subcategoryId: 'sub-rec-salario',
      accountId: 'acc-demo-itau',
      userId: 'mem-demo-owner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['salario', 'fixo'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-rec-bonus',
      description: 'Bônus / PLR Semestral',
      amount: 4200.00,
      date: getDateInCurrentMonth(10),
      type: 'income',
      status: 'completed',
      categoryId: 'cat-rec-trabalho',
      subcategoryId: 'sub-rec-bonus',
      accountId: 'acc-demo-itau',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['bonus', 'plr'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-rec-fiis',
      description: 'Dividendos FIIs (HGLG11 / MXRF11)',
      amount: 542.80,
      date: getDateInCurrentMonth(15),
      type: 'income',
      status: 'completed',
      categoryId: 'cat-rec-investimentos',
      subcategoryId: 'sub-rec-dividendos',
      accountId: 'acc-demo-xp',
      userId: 'mem-demo-owner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['dividendos', 'renda_passiva'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-rec-freelance',
      description: 'Consultoria Web / Projeto React Native',
      amount: 1850.00,
      date: getDateInCurrentMonth(18),
      type: 'income',
      status: 'completed',
      categoryId: 'cat-rec-freelance',
      subcategoryId: 'sub-rec-freelance',
      accountId: 'acc-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['extra', 'freelance'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-rec-cashback',
      description: 'Cashback Cartão Ultravioleta',
      amount: 74.30,
      date: getDateInCurrentMonth(22),
      type: 'income',
      status: 'completed',
      categoryId: 'cat-rec-beneficios-outras',
      subcategoryId: 'sub-rec-cashback',
      accountId: 'acc-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['cashback'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-rec-restituicao',
      description: 'Restituição de Imposto de Renda (Lote 2)',
      amount: 1450.00,
      date: getDateInCurrentMonth(25),
      type: 'income',
      status: 'completed',
      categoryId: 'cat-rec-beneficios-outras',
      subcategoryId: 'sub-rec-restituicao-ir',
      accountId: 'acc-demo-itau',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['imposto', 'restituicao'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-rec-reembolso-ana',
      description: 'Reembolso Recebido - Ana Clara (Amigo Secreto)',
      amount: 90.00,
      date: getDateInCurrentMonth(12),
      type: 'income',
      status: 'completed',
      categoryId: 'cat-rec-beneficios-outras',
      subcategoryId: 'sub-rec-reembolsos',
      accountId: 'acc-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['reembolso', 'terceiro'],
      createdAt: now.toISOString(),
    },

    // --- TRANSFERÊNCIAS ENTRE CONTAS BANCÁRIAS (type: 'transfer') ---
    {
      id: 'tx-transf-reserva-xp',
      description: 'Aporte Mensal Tesouro & FIIs',
      amount: 1500.00,
      date: getDateInCurrentMonth(6),
      type: 'transfer',
      status: 'completed',
      accountId: 'acc-demo-itau',
      targetAccountId: 'acc-demo-xp',
      categoryId: 'cat-mov-transferencias',
      subcategoryId: 'sub-mov-transf-contas',
      userId: 'mem-demo-owner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['transferencia', 'aporte', 'investimento'],
      createdAt: now.toISOString(),
    },

    // --- DESPESAS FIXAS REPETIDAS EM CONTA ---
    {
      id: 'tx-desp-aluguel',
      description: 'Aluguel do Apartamento',
      amount: 2400.00,
      date: getDateInCurrentMonth(10),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-moradia',
      subcategoryId: 'sub-mor-aluguel',
      accountId: 'acc-demo-itau',
      userId: 'mem-demo-owner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['fixo', 'moradia'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-condominio',
      description: 'Condomínio Residencial Jardim',
      amount: 720.00,
      date: getDateInCurrentMonth(10),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-moradia',
      subcategoryId: 'sub-mor-condominio',
      accountId: 'acc-demo-itau',
      userId: 'mem-demo-owner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['fixo', 'moradia'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-energia',
      description: 'Energia Elétrica Enel',
      amount: 238.40,
      date: getDateInCurrentMonth(14),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-moradia',
      subcategoryId: 'sub-mor-energia',
      accountId: 'acc-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['utilidades'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-internet',
      description: 'Internet Fibra 600MB Vivo',
      amount: 119.90,
      date: getDateInCurrentMonth(12),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-moradia',
      subcategoryId: 'sub-mor-internet',
      accountId: 'acc-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['internet'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-diarista',
      description: 'Faxina e Diarista Quinzenal',
      amount: 360.00,
      date: getDateInCurrentMonth(15),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-moradia',
      subcategoryId: 'sub-mor-diarista',
      accountId: 'acc-demo-carteira',
      userId: 'mem-demo-partner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['casa', 'limpeza'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-saude',
      description: 'Plano de Saúde Unimed Família',
      amount: 490.00,
      date: getDateInCurrentMonth(15),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-saude',
      subcategoryId: 'sub-saude-plano',
      accountId: 'acc-demo-itau',
      userId: 'mem-demo-owner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['saude'],
      createdAt: now.toISOString(),
    },

    // --- ASSINATURAS E CLUBES DE BENEFÍCIOS (NOVA SUBCATEGORIA 📦) ---
    {
      id: 'tx-desp-meli-plus',
      description: 'Assinatura Meli+ Mercado Livre / Disney+',
      amount: 17.99,
      date: getDateInCurrentMonth(5),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-compras-pessoal',
      subcategoryId: 'sub-comp-clubes-assinaturas',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['assinatura', 'meli_plus', 'beneficios'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-clube-livelo',
      description: 'Clube Livelo 3.000 Pontos Mensais',
      amount: 129.90,
      date: getDateInCurrentMonth(8),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-compras-pessoal',
      subcategoryId: 'sub-comp-clubes-assinaturas',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['pontos', 'milhas', 'beneficios'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-academia',
      description: 'Academia Smart Fit Black',
      amount: 129.90,
      date: getDateInCurrentMonth(8),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-academia-esportes',
      subcategoryId: 'sub-acad-academia',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['academia'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-streamings',
      description: 'Streaming Netflix 4K + Spotify Família',
      amount: 94.80,
      date: getDateInCurrentMonth(3),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-lazer',
      subcategoryId: 'sub-lazer-streaming',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['streaming'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-plano-celular',
      description: 'Plano Celular Claro 5G Pós-Pago',
      amount: 79.90,
      date: getDateInCurrentMonth(7),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-compras-pessoal',
      subcategoryId: 'sub-comp-plano-cel',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['celular', 'telefonia'],
      createdAt: now.toISOString(),
    },

    // --- TRANSAÇÕES COM TERCEIROS (DIVIDIR GASTOS / REEMBOLSO) ---
    // 1. Pendente de reembolso (Lucas Lima deve R$ 145,00) -> Ativa o botão "Receber Reembolso"
    {
      id: 'tx-desp-terceiro-lucas',
      description: 'Almoço de Domingo com Amigos (Parte do Lucas)',
      amount: 145.00,
      date: getDateInCurrentMonth(11),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-alimentacao',
      subcategoryId: 'sub-alim-restaurante',
      cardId: 'card-demo-itau',
      userId: 'mem-demo-owner',
      recurring: false,
      isThirdParty: true,
      thirdPartyName: 'Lucas Lima',
      thirdPartyAmount: 145.00,
      reimbursed: false,
      tags: ['terceiro', 'reembolsar', 'amigos'],
      notes: 'Lucas vai pagar via Pix até o fim da semana',
      createdAt: now.toISOString(),
    },
    // 2. Já reembolsada (Ana Clara já pagou)
    {
      id: 'tx-desp-terceiro-ana',
      description: 'Presente Amigo Secreto (Parte da Ana)',
      amount: 90.00,
      date: getDateInCurrentMonth(9),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-compras-pessoal',
      subcategoryId: 'sub-comp-presentes',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: false,
      isThirdParty: true,
      thirdPartyName: 'Ana Clara',
      thirdPartyAmount: 90.00,
      reimbursed: true,
      tags: ['terceiro', 'reembolsado'],
      createdAt: now.toISOString(),
    },

    // --- TRANSAÇÃO IGNORADA (ignored: true - Estorno ou Lançamento Neutro) ---
    {
      id: 'tx-desp-estorno-ignorado',
      description: 'Estorno Parcial de Cobrança Duplicada Lojista',
      amount: 65.00,
      date: getDateInCurrentMonth(13),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-compras-pessoal',
      subcategoryId: 'sub-comp-eletronicos',
      cardId: 'card-demo-c6',
      userId: 'mem-demo-owner',
      recurring: false,
      ignored: true,
      tags: ['ignorado', 'estorno'],
      notes: 'Lançamento estornado pela operadora, ignorado dos relatórios',
      createdAt: now.toISOString(),
    },

    // --- PARCELAMENTOS ATIVOS NO CARTÃO (MÊS ATUAL + FUTUROS) ---
    // 1. MacBook Pro M3 (10 parcelas de R$ 849.90 - Parcela 3 no mês atual)
    ...Array.from({ length: 10 }).map((_, idx) => {
      const pNum = idx + 1;
      const mOffset = idx - 2;
      const pMonth = getOffsetMonthPrefix(mOffset);
      const isPastOrCurrent = mOffset <= 0;

      return {
        id: `tx-parc-macbook-p${pNum}`,
        description: `MacBook Pro M3 Apple Store (${pNum}/10)`,
        amount: 849.90,
        date: `${pMonth}-15`,
        type: 'expense' as const,
        status: (isPastOrCurrent ? 'completed' : 'pending') as 'completed' | 'pending',
        categoryId: 'cat-desp-compras-pessoal',
        subcategoryId: 'sub-comp-informatica',
        cardId: 'card-demo-nubank',
        userId: 'mem-demo-owner',
        recurring: false,
        installments: { current: pNum, total: 10 },
        tags: ['parcelado', 'apple', 'trabalho'],
        createdAt: now.toISOString(),
      };
    }),

    // 2. iPhone 16 Pro Max (12 parcelas de R$ 649.90 - Parcela 2 no mês atual)
    ...Array.from({ length: 12 }).map((_, idx) => {
      const pNum = idx + 1;
      const mOffset = idx - 1;
      const pMonth = getOffsetMonthPrefix(mOffset);
      const isPastOrCurrent = mOffset <= 0;

      return {
        id: `tx-parc-iphone-p${pNum}`,
        description: `iPhone 16 Pro Max Titanium (${pNum}/12)`,
        amount: 649.90,
        date: `${pMonth}-10`,
        type: 'expense' as const,
        status: (isPastOrCurrent ? 'completed' : 'pending') as 'completed' | 'pending',
        categoryId: 'cat-desp-compras-pessoal',
        subcategoryId: 'sub-comp-celular',
        cardId: 'card-demo-itau',
        userId: 'mem-demo-partner',
        recurring: false,
        installments: { current: pNum, total: 12 },
        tags: ['parcelado', 'iphone'],
        createdAt: now.toISOString(),
      };
    }),

    // 3. Passagens Aéreas Férias Europa (6 parcelas de R$ 416.50 - Parcela 1 no mês atual)
    ...Array.from({ length: 6 }).map((_, idx) => {
      const pNum = idx + 1;
      const mOffset = idx;
      const pMonth = getOffsetMonthPrefix(mOffset);
      const isPastOrCurrent = mOffset <= 0;

      return {
        id: `tx-parc-passagens-p${pNum}`,
        description: `Passagens Aéreas Férias Europa (${pNum}/6)`,
        amount: 416.50,
        date: `${pMonth}-08`,
        type: 'expense' as const,
        status: (isPastOrCurrent ? 'completed' : 'pending') as 'completed' | 'pending',
        categoryId: 'cat-desp-lazer',
        subcategoryId: 'sub-lazer-viagens',
        cardId: 'card-demo-c6',
        userId: 'mem-demo-owner',
        recurring: false,
        installments: { current: pNum, total: 6 },
        tags: ['viagem', 'ferias'],
        createdAt: now.toISOString(),
      };
    }),

    // 4. Jogo de 4 Pneus Michelin (5 parcelas de R$ 320.00 - Parcela 4 no mês atual)
    ...Array.from({ length: 5 }).map((_, idx) => {
      const pNum = idx + 1;
      const mOffset = idx - 3;
      const pMonth = getOffsetMonthPrefix(mOffset);
      const isPastOrCurrent = mOffset <= 0;

      return {
        id: `tx-parc-pneus-p${pNum}`,
        description: `Pneus Michelin Carro (${pNum}/5)`,
        amount: 320.00,
        date: `${pMonth}-18`,
        type: 'expense' as const,
        status: (isPastOrCurrent ? 'completed' : 'pending') as 'completed' | 'pending',
        categoryId: 'cat-desp-transporte',
        subcategoryId: 'sub-trans-manutencao',
        cardId: 'card-demo-nubank',
        userId: 'mem-demo-owner',
        recurring: false,
        installments: { current: pNum, total: 5 },
        tags: ['carro', 'manutencao'],
        createdAt: now.toISOString(),
      };
    }),

    // 5. Sofá Retrátil Mobly Sala (8 parcelas de R$ 285.00 - Parcela 3 no mês atual)
    ...Array.from({ length: 8 }).map((_, idx) => {
      const pNum = idx + 1;
      const mOffset = idx - 2;
      const pMonth = getOffsetMonthPrefix(mOffset);
      const isPastOrCurrent = mOffset <= 0;

      return {
        id: `tx-parc-sofa-p${pNum}`,
        description: `Sofá Retrátil 4 Lugares Mobly (${pNum}/8)`,
        amount: 285.00,
        date: `${pMonth}-14`,
        type: 'expense' as const,
        status: (isPastOrCurrent ? 'completed' : 'pending') as 'completed' | 'pending',
        categoryId: 'cat-desp-moradia',
        subcategoryId: 'sub-mor-moveis',
        cardId: 'card-demo-itau',
        userId: 'mem-demo-partner',
        recurring: false,
        installments: { current: pNum, total: 8 },
        tags: ['casa', 'moveis'],
        createdAt: now.toISOString(),
      };
    }),

    // --- DESPESAS VARIÁVEIS DO DIA A DIA NO MÊS ATUAL ---
    {
      id: 'tx-desp-mercado-1',
      description: 'Supermercado Pão de Açúcar (Compras Quinzenais)',
      amount: 512.30,
      date: getDateInCurrentMonth(4),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-alimentacao',
      subcategoryId: 'sub-alim-mercado',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['mercado', 'casa'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-mercado-2',
      description: 'Mercado Express e Carnes',
      amount: 320.40,
      date: getDateInCurrentMonth(16),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-alimentacao',
      subcategoryId: 'sub-alim-mercado',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-partner',
      recurring: false,
      tags: ['mercado'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-hortifruti',
      description: 'Feira Livre e Hortifruti Fresco',
      amount: 94.50,
      date: getDateInCurrentMonth(14),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-alimentacao',
      subcategoryId: 'sub-alim-hortifruti',
      accountId: 'acc-demo-carteira',
      userId: 'mem-demo-partner',
      recurring: false,
      tags: ['feira', 'saude'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-delivery-ifood',
      description: 'iFood - Jantar Pizza Sexta-Feira',
      amount: 89.90,
      date: getDateInCurrentMonth(17),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-alimentacao',
      subcategoryId: 'sub-alim-delivery',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['delivery', 'ifood', 'fimdesemana'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-restaurante',
      description: 'Jantar Restaurante Coco Bambu',
      amount: 245.00,
      date: getDateInCurrentMonth(11),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-alimentacao',
      subcategoryId: 'sub-alim-restaurante',
      cardId: 'card-demo-itau',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['lazer', 'jantar'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-padaria',
      description: 'Padaria e Café Artesanal',
      amount: 38.50,
      date: getDateInCurrentMonth(19),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-alimentacao',
      subcategoryId: 'sub-alim-padaria',
      cardId: 'card-demo-c6',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['cafe', 'padaria'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-posto-shell',
      description: 'Combustível Shell V-Power',
      amount: 260.00,
      date: getDateInCurrentMonth(7),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-transporte',
      subcategoryId: 'sub-trans-combustivel',
      cardId: 'card-demo-c6',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['combustivel', 'carro'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-uber',
      description: 'Uber Corridas da Semana Reuniões',
      amount: 58.40,
      date: getDateInCurrentMonth(9),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-transporte',
      subcategoryId: 'sub-trans-uber',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['transporte', 'uber'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-estacionamento',
      description: 'Estacionamento Shopping Iguatemi',
      amount: 24.00,
      date: getDateInCurrentMonth(12),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-transporte',
      subcategoryId: 'sub-trans-estacionamento',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-partner',
      recurring: false,
      tags: ['estacionamento'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-pedagio',
      description: 'Pedágio Rodovia dos Imigrantes',
      amount: 33.80,
      date: getDateInCurrentMonth(20),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-transporte',
      subcategoryId: 'sub-trans-pedagio',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['pedagio', 'viagem'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-farmacia',
      description: 'Farmácia Drogasil (Vitaminas & Higiene)',
      amount: 92.40,
      date: getDateInCurrentMonth(13),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-saude',
      subcategoryId: 'sub-saude-farmacia',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-partner',
      recurring: false,
      tags: ['farmacia', 'saude'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-dentista',
      description: 'Consulta Odontológica e Limpeza',
      amount: 250.00,
      date: getDateInCurrentMonth(18),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-saude',
      subcategoryId: 'sub-saude-odonto',
      accountId: 'acc-demo-itau',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['saude', 'dentista'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-suplementos',
      description: 'Growth Suplementos (Whey Protein & Creatina)',
      amount: 185.00,
      date: getDateInCurrentMonth(15),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-academia-esportes',
      subcategoryId: 'sub-acad-suplementos',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['treino', 'suplementos'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-livros',
      description: 'Livros de Arquitetura & Finanças Amazon',
      amount: 124.00,
      date: getDateInCurrentMonth(10),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-educacao',
      subcategoryId: 'sub-educ-livros',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-owner',
      recurring: false,
      tags: ['estudos', 'livros'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-cinema',
      description: 'Ingressos Cinema IMAX Cinépolis',
      amount: 82.00,
      date: getDateInCurrentMonth(16),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-lazer',
      subcategoryId: 'sub-lazer-cinema',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-partner',
      recurring: false,
      tags: ['cinema', 'lazer'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-cobasi',
      description: 'Cobasi Ração Golden & Petiscos Pet',
      amount: 168.00,
      date: getDateInCurrentMonth(14),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-pets',
      subcategoryId: 'sub-pets-racao',
      cardId: 'card-demo-nubank',
      userId: 'mem-demo-partner',
      recurring: false,
      tags: ['pets', 'racao'],
      createdAt: now.toISOString(),
    },
    {
      id: 'tx-desp-dizimo',
      description: 'Dízimo / Contribuição Comunitária',
      amount: 250.00,
      date: getDateInCurrentMonth(8),
      type: 'expense',
      status: 'completed',
      categoryId: 'cat-desp-igreja-doacoes',
      subcategoryId: 'sub-igreja-dizimos',
      accountId: 'acc-demo-itau',
      userId: 'mem-demo-owner',
      recurring: true,
      recurrenceFrequency: 'monthly',
      tags: ['doacoes', 'igreja'],
      createdAt: now.toISOString(),
    },
  ];

  // 6. BUDGETS (Orçamentos por Categoria para os 12 meses do ano)
  const baseBudgets = [
    { catId: 'cat-rec-trabalho', limit: 12000.00 },
    { catId: 'cat-desp-alimentacao', limit: 2000.00 },
    { catId: 'cat-desp-moradia', limit: 3800.00 },
    { catId: 'cat-desp-transporte', limit: 1200.00 },
    { catId: 'cat-desp-lazer', limit: 900.00 },
    { catId: 'cat-desp-saude', limit: 850.00 },
    { catId: 'cat-desp-compras-pessoal', limit: 2200.00 },
    { catId: 'cat-desp-educacao', limit: 500.00 },
    { catId: 'cat-desp-academia-esportes', limit: 350.00 },
    { catId: 'cat-desp-pets', limit: 300.00 },
  ];

  const budgets: Budget[] = [];
  for (let m = 1; m <= 12; m++) {
    const monthStr = `${year}-${String(m).padStart(2, '0')}`;
    baseBudgets.forEach(b => {
      budgets.push({
        id: `bud-${b.catId}-${monthStr}`,
        categoryId: b.catId,
        limit: b.limit,
        month: monthStr,
      });
    });
  }

  // 7. METAS FINANCEIRAS (Goals com histórico de depósitos)
  const goals: Goal[] = [
    {
      id: 'goal-reserva-emergencia',
      title: 'Reserva de Emergência (6 Meses)',
      description: '6 meses de custo de vida para total tranquilidade financeira',
      targetAmount: 35000.00,
      currentAmount: 24000.00,
      deadline: `${year}-12-31`,
      icon: '🛡️',
      color: '#10b981',
      completed: false,
      status: 'active',
      deposits: [
        { id: 'dep-1', amount: 15000.00, date: `${year}-01-15`, note: 'Aporte Inicial da Poupança' },
        { id: 'dep-2', amount: 4000.00, date: `${year}-02-10`, note: 'Sobra do 13º e PLR' },
        { id: 'dep-3', amount: 2500.00, date: `${year}-03-05`, note: 'Aporte Mensal Recorrente' },
        { id: 'dep-4', amount: 2500.00, date: getDateInCurrentMonth(5), note: 'Aporte do Mês Vigente' },
      ],
    },
    {
      id: 'goal-viagem-europa',
      title: 'Férias Europa 2027',
      description: 'Roteiro Itália, França e Suíça com a família',
      targetAmount: 20000.00,
      currentAmount: 9500.00,
      deadline: '2027-07-31',
      icon: '✈️',
      color: '#3b82f6',
      completed: false,
      status: 'active',
      deposits: [
        { id: 'dep-v1', amount: 5000.00, date: `${year}-01-20`, note: 'Início do Planejamento' },
        { id: 'dep-v2', amount: 2500.00, date: `${year}-02-25`, note: 'Rendimento de Freelance' },
        { id: 'dep-v3', amount: 2000.00, date: getDateInCurrentMonth(10), note: 'Aporte Mensal Viagem' },
      ],
    },
    {
      id: 'goal-troca-carro',
      title: 'Troca de Carro (SUV Híbrido)',
      description: 'Poupança para entrada do SUV Híbrido',
      targetAmount: 50000.00,
      currentAmount: 18000.00,
      deadline: '2028-06-30',
      icon: '🚗',
      color: '#7c4dff',
      completed: false,
      status: 'active',
      deposits: [
        { id: 'dep-c1', amount: 15000.00, date: `${year}-01-05`, note: 'Valor Inicial da Troca' },
        { id: 'dep-c2', amount: 3000.00, date: getDateInCurrentMonth(1), note: 'Aporte de Rendimentos' },
      ],
    },
    {
      id: 'goal-mobilia-apto',
      title: 'Mobília & Decoração do Apartamento',
      description: 'Planejados para cozinha e área gourmet',
      targetAmount: 25000.00,
      currentAmount: 11000.00,
      deadline: `${year}-11-30`,
      icon: '🛋️',
      color: '#f59e0b',
      completed: false,
      status: 'active',
      deposits: [
        { id: 'dep-m1', amount: 8000.00, date: `${year}-01-10`, note: 'Entrada reservada' },
        { id: 'dep-m2', amount: 3000.00, date: getDateInCurrentMonth(15), note: 'Aporte de Bônus' },
      ],
    },
    {
      id: 'goal-curso-concluido',
      title: 'Certificação Internacional Cloud Tech',
      description: 'AWS Certified Solutions Architect + Treinamentos',
      targetAmount: 4500.00,
      currentAmount: 4500.00,
      deadline: `${year}-02-28`,
      icon: '🎓',
      color: '#06b6d4',
      completed: true,
      status: 'completed',
      deposits: [
        { id: 'dep-e1', amount: 2500.00, date: `${year}-01-05`, note: 'Inscrição e Materiais' },
        { id: 'dep-e2', amount: 2000.00, date: `${year}-02-15`, note: 'Prova e Laboratórios' },
      ],
    },
  ];

  // 8. DÍVIDAS E FINANCIAMENTOS (Debts com sistemas SAC e Price + TR)
  const debts: Debt[] = [
    {
      id: 'debt-financiamento-caixa',
      title: 'Financiamento Imobiliário Caixa',
      creditor: 'Caixa Econômica Federal',
      contractType: 'real_estate',
      contractNumber: 'CAIXA-SFH-2024-001',
      totalAmount: 200000.00,
      remainingAmount: 182000.00,
      interestRate: 9.5,
      amortizationSystem: 'PRICE',
      indexer: 'TR',
      indexerRate: 0.1708,
      insuranceMonthly: 38.50,
      adminFeeMonthly: 25.00,
      totalInstallments: 360,
      paidInstallments: 28,
      installmentAmount: 1520.00,
      dueDay: 15,
      nextDueDate: getDateInCurrentMonth(15),
      defaultAccountId: 'acc-demo-itau',
      syncToTransactions: true,
      payments: [
        { id: 'pay-d1', amount: 1520.00, date: getDateInCurrentMonth(15), installmentNumber: 28 },
        {
          id: 'pay-d-extra',
          amount: 5000.00,
          date: getDateInOffsetMonth(-1, 20),
          installmentNumber: 27,
          amortizationAmount: 5000.00,
          remainingBalanceAfter: 183520.00,
        },
      ],
    },
    {
      id: 'debt-veiculo-sac',
      title: 'Financiamento Veicular SUV',
      creditor: 'Banco Santander Financiamentos',
      contractType: 'vehicle',
      contractNumber: 'SAN-AUTO-2023-889',
      totalAmount: 55000.00,
      remainingAmount: 38500.00,
      interestRate: 11.8,
      amortizationSystem: 'SAC',
      indexer: 'FIXED',
      indexerRate: 0,
      insuranceMonthly: 0,
      adminFeeMonthly: 0,
      totalInstallments: 48,
      paidInstallments: 14,
      installmentAmount: 1120.00,
      dueDay: 20,
      nextDueDate: getDateInCurrentMonth(20),
      defaultAccountId: 'acc-demo-nubank',
      syncToTransactions: true,
      payments: [
        { id: 'pay-d2', amount: 1120.00, date: getDateInCurrentMonth(20), installmentNumber: 14 },
      ],
    },
    {
      id: 'debt-emprestimo-inter',
      title: 'Empréstimo Pessoal Reforma',
      creditor: 'Banco Inter',
      contractType: 'loan',
      contractNumber: 'INTER-LOAN-2024-412',
      totalAmount: 12000.00,
      remainingAmount: 6800.00,
      interestRate: 14.5,
      amortizationSystem: 'PRICE',
      indexer: 'FIXED',
      totalInstallments: 24,
      paidInstallments: 10,
      installmentAmount: 680.00,
      dueDay: 25,
      nextDueDate: getDateInCurrentMonth(25),
      defaultAccountId: 'acc-demo-inter',
      syncToTransactions: true,
      payments: [
        { id: 'pay-d3', amount: 680.00, date: getDateInCurrentMonth(25), installmentNumber: 10 },
      ],
    },
  ];

  // Gera parcelas sincronizadas no extrato para as dívidas
  debts.forEach(debt => {
    const remainingInstallments = Math.min(12, debt.totalInstallments - debt.paidInstallments);
    for (let offset = 0; offset < remainingInstallments; offset++) {
      const installmentNumber = debt.paidInstallments + offset + 1;
      const dueDate = getDateInOffsetMonth(offset, debt.dueDay);
      const isRealEstate = debt.contractType === 'real_estate';
      const isVehicle = debt.contractType === 'vehicle';

      // No sistema SAC, parcelas futuras vão reduzindo ligeiramente
      let calculatedAmount = debt.installmentAmount;
      if (debt.amortizationSystem === 'SAC') {
        calculatedAmount = Math.max(100, Math.round((debt.installmentAmount - (offset * 12.50)) * 100) / 100);
      }

      transactions.push({
        id: `tx-debt-${debt.id}-${installmentNumber}`,
        description: `${debt.title} (${installmentNumber}/${debt.totalInstallments})`,
        amount: calculatedAmount,
        type: 'expense',
        date: dueDate,
        dueDate,
        categoryId: isRealEstate
          ? 'cat-desp-moradia'
          : isVehicle
          ? 'cat-desp-transporte'
          : 'cat-desp-financeiro',
        subcategoryId: isRealEstate
          ? 'sub-mor-financiamento-apto'
          : isVehicle
          ? 'sub-trans-financiamento'
          : 'sub-fin-pagamento-dividas',
        accountId: debt.defaultAccountId,
        userId: 'mem-demo-owner',
        status: 'pending',
        recurring: false,
        installments: { current: installmentNumber, total: debt.totalInstallments },
        debtId: debt.id,
        debtInstallmentNumber: installmentNumber,
        tags: ['financiamento', 'parcela'],
        notes: debt.contractNumber ? `Contrato nº ${debt.contractNumber}` : undefined,
        createdAt: now.toISOString(),
      });
    }
  });

  // 9. INVESTIMENTOS (Investment Assets - Cobrindo todas as 5 classes)
  const investments: InvestmentAsset[] = [
    {
      id: 'inv-tesouro-ipca',
      name: 'Tesouro IPCA+ 2035',
      ticker: 'IPCA2035',
      type: 'fixed',
      institution: 'XP Investimentos',
      investedAmount: 14200.00,
      currentBalance: 15680.00,
      monthlyYield: 128.00,
      yieldPercentage: 10.4,
      updatedAt: now.toISOString(),
    },
    {
      id: 'inv-cdb-cdi',
      name: 'CDB 110% do CDI Liquidez Diária',
      ticker: 'CDB-NUBANK',
      type: 'fixed',
      institution: 'Nubank',
      investedAmount: 10500.00,
      currentBalance: 11150.00,
      monthlyYield: 98.50,
      yieldPercentage: 6.19,
      updatedAt: now.toISOString(),
    },
    {
      id: 'inv-fii-hglg',
      name: 'CSHG Logística FII',
      ticker: 'HGLG11',
      type: 'fiis',
      institution: 'XP Investimentos',
      investedAmount: 9150.00,
      currentBalance: 9840.00,
      quantity: 60,
      averagePrice: 152.50,
      currentPrice: 164.00,
      monthlyYield: 82.40,
      yieldPercentage: 8.54,
      updatedAt: now.toISOString(),
    },
    {
      id: 'inv-fii-mxrf',
      name: 'Maxi Renda FII',
      ticker: 'MXRF11',
      type: 'fiis',
      institution: 'XP Investimentos',
      investedAmount: 4800.00,
      currentBalance: 5120.00,
      quantity: 500,
      averagePrice: 9.60,
      currentPrice: 10.24,
      monthlyYield: 48.00,
      yieldPercentage: 11.25,
      updatedAt: now.toISOString(),
    },
    {
      id: 'inv-acao-itsa',
      name: 'Itaúsa S.A.',
      ticker: 'ITSA4',
      type: 'stocks',
      institution: 'XP Investimentos',
      investedAmount: 6400.00,
      currentBalance: 7280.00,
      quantity: 700,
      averagePrice: 9.14,
      currentPrice: 10.40,
      monthlyYield: 52.00,
      yieldPercentage: 13.75,
      updatedAt: now.toISOString(),
    },
    {
      id: 'inv-acao-wege',
      name: 'WEG S.A.',
      ticker: 'WEGE3',
      type: 'stocks',
      institution: 'XP Investimentos',
      investedAmount: 5200.00,
      currentBalance: 6150.00,
      quantity: 120,
      averagePrice: 43.33,
      currentPrice: 51.25,
      monthlyYield: 38.00,
      yieldPercentage: 18.27,
      updatedAt: now.toISOString(),
    },
    {
      id: 'inv-crypto-btc',
      name: 'Bitcoin (Reserva Descentralizada)',
      ticker: 'BTC',
      type: 'crypto',
      institution: 'Nubank Cripto',
      investedAmount: 7000.00,
      currentBalance: 8850.00,
      quantity: 0.0245,
      averagePrice: 285714.00,
      currentPrice: 361224.00,
      monthlyYield: 0,
      yieldPercentage: 26.43,
      updatedAt: now.toISOString(),
    },
    {
      id: 'inv-fundo-trend',
      name: 'Trend Inflação Curta FI Renda Fixa',
      ticker: 'TREND-INF',
      type: 'funds',
      institution: 'XP Investimentos',
      investedAmount: 5000.00,
      currentBalance: 5320.00,
      monthlyYield: 42.00,
      yieldPercentage: 6.4,
      updatedAt: now.toISOString(),
    },
  ];

  // 10. NOTIFICAÇÕES (NotificationItem)
  const notifications: NotificationItem[] = [
    {
      id: 'notif-1',
      title: 'Fatura Fechada: Nubank Ultravioleta',
      message: 'Sua fatura fechou em R$ 2.418,50 com vencimento em 05 deste mês. O pagamento automático está programado.',
      date: getDateInCurrentMonth(1),
      read: false,
      type: 'info',
      tag: 'cartao',
    },
    {
      id: 'notif-2',
      title: 'Meta de Reserva Ultrapassou 68%',
      message: 'Parabéns! Sua meta "Reserva de Emergência" atingiu R$ 24.000,00 de R$ 35.000,00 estipulados.',
      date: getDateInCurrentMonth(5),
      read: false,
      type: 'success',
      tag: 'meta',
    },
    {
      id: 'notif-3',
      title: 'Lembrete: Financiamento Imobiliário Caixa',
      message: 'A parcela nº 28 do contrato SFH-2024 vence no dia 15 na sua conta Itaú Personnalité.',
      date: getDateInCurrentMonth(12),
      read: false,
      type: 'reminder',
      tag: 'divida',
    },
    {
      id: 'notif-4',
      title: 'Atenção ao Orçamento de Alimentação',
      message: 'Você já utilizou 78% do orçamento mensal estipulado para a categoria Alimentação.',
      date: getDateInCurrentMonth(16),
      read: true,
      type: 'alert',
      tag: 'orcamento',
    },
  ];

  // 11. SÉRIES RECORRENTES (TransactionSeries)
  const transactionSeries: TransactionSeries[] = [
    {
      id: 'series-aluguel',
      kind: 'recurring_expense',
      description: 'Aluguel do Apartamento',
      categoryId: 'cat-desp-moradia',
      subcategoryId: 'sub-mor-aluguel',
      startDate: `${year}-01-10`,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      frequency: 'monthly',
      interval: 1,
      expectedAmount: 2400.00,
      paymentMethod: 'account',
      accountId: 'acc-demo-itau',
    } as any,
    {
      id: 'series-condominio',
      kind: 'recurring_expense',
      description: 'Condomínio Residencial Jardim',
      categoryId: 'cat-desp-moradia',
      subcategoryId: 'sub-mor-condominio',
      startDate: `${year}-01-10`,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      frequency: 'monthly',
      interval: 1,
      expectedAmount: 720.00,
      paymentMethod: 'account',
      accountId: 'acc-demo-itau',
    } as any,
    {
      id: 'series-smartfit',
      kind: 'recurring_expense',
      description: 'Academia Smart Fit Black',
      categoryId: 'cat-desp-academia-esportes',
      subcategoryId: 'sub-acad-academia',
      startDate: `${year}-01-08`,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      frequency: 'monthly',
      interval: 1,
      expectedAmount: 129.90,
      paymentMethod: 'card',
      cardId: 'card-demo-nubank',
    } as any,
    {
      id: 'series-internet',
      kind: 'recurring_expense',
      description: 'Internet Fibra 600MB Vivo',
      categoryId: 'cat-desp-moradia',
      subcategoryId: 'sub-mor-internet',
      startDate: `${year}-01-12`,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      frequency: 'monthly',
      interval: 1,
      expectedAmount: 119.90,
      paymentMethod: 'account',
      accountId: 'acc-demo-nubank',
    } as any,
  ];

  return {
    accounts,
    cards,
    categories,
    transactions,
    transactionSeries,
    budgets,
    goals,
    debts,
    investments,
    familyMembers,
    notifications,
    userProfile: {
      name: 'Carlos Eduardo (Você)',
      email: 'demo@finly.com',
      phone: '(11) 99999-8888',
      currency: 'BRL',
      showValues: true,
    },
  };
}
